## This redirects to other doc branches

[[redirects]]
  from = "/6.2/*"
  to = "https://docs.thoughtspot.com/6.2/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/6.1/*"
  to = "https://docs.thoughtspot.com/6.1/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/6.0/*"
  to = "https://docs.thoughtspot.com/6.0/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/5.3/*"
  to = "https://docs.thoughtspot.com/5.3/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/5.2/*"
  to = "https://docs.thoughtspot.com/5.2/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/5.1/*"
  to = "https://docs.thoughtspot.com/5.1/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/5.0/*"
  to = "https://docs.thoughtspot.com/5.0/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/4.5/*"
  to = "https://docs.thoughtspot.com/4.5/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/4.4/*"
  to = "https://docs.thoughtspot.com/4.5/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
