# .github/workflows/daily-build-workflow.yml

name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 18 * * 1,2,3,4,5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5de8a09d3b6918a75905fe84
